FROM rocker/tidyverse:latest

LABEL org.opencontainers.image.licenses="GPL-2.0-or-later" \
      org.opencontainers.image.source="https://github.com/rocker-org/rocker-versioned2" \
      org.opencontainers.image.vendor="Rocker Project" \
      org.opencontainers.image.authors="Carl Boettiger <cboettig@ropensci.org>"


RUN install2.r --error --deps TRUE --skipmissing --skipinstalled \
    BiocManager\
    rmarkdown \
    tidyverse \
    dplyr \
    knitr \
    airway \
    SummarizedExperiment \
    DESeq2 \
    DelayedArray \
    vsn \
    ggplot2 \
    hexbin \
    pheatmap \
    RColorBrewer \
    ggbeeswarm \
    apeglm \
    ggrepel \
    AnnotationDbi \
    org.Hs.eg.db \
    clusterProfiler \
    enrichplot \
    && rm -rf /tmp/downloaded_packages
