FROM rocker/tidyverse:latest

LABEL org.opencontainers.image.licenses="GPL-2.0-or-later" \
      org.opencontainers.image.source="https://github.com/rocker-org/rocker-versioned2" \
      org.opencontainers.image.vendor="Rocker Project" \
      org.opencontainers.image.authors="Carl Boettiger <cboettig@ropensci.org>"


RUN install2.r --error --skipinstalled --ncpus -1 \
    BiocManager\
    rmarkdown \
    tidyverse \
    dplyr \
    knitr \
    ggplot2 \
    hexbin \
    pheatmap \
    RColorBrewer \
    ggbeeswarm \
    ggrepel \
    && rm -rf /tmp/downloaded_packages \
    && strip /usr/local/lib/R/site-library/*/libs/*.so

EXPOSE 8787


CMD ["/init"]